# Generated by Django 3.1.1 on 2020-11-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201109_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('inactive', 'inactive')], max_length=30, null=True),
        ),
    ]
