# Generated by Django 3.1.1 on 2020-11-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201109_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
