# Generated by Django 3.1.1 on 2020-11-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201109_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
            ],
        ),
        migrations.RenameModel(
            old_name='Admin',
            new_name='Monitor',
        ),
        migrations.DeleteModel(
            name='Admin_Faculty',
        ),
        migrations.AddField(
            model_name='monitor_faculty',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.monitor'),
        ),
    ]
