# Generated by Django 3.1.1 on 2020-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201110_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
