# Generated by Django 3.1.1 on 2020-11-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201110_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_student',
            name='Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Denied')], max_length=30, null='Pending'),
        ),
    ]
