# Generated by Django 3.1.1 on 2020-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201129_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_student',
            name='Student_Reflection',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
