# Generated by Django 3.1.1 on 2020-12-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='faculty',
        ),
        migrations.AddField(
            model_name='user',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
    ]
