# Generated by Django 3.1.1 on 2020-12-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201130_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='faculty',
            new_name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monitor',
        ),
    ]
