# Generated by Django 3.1.1 on 2020-11-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('length', models.FloatField()),
                ('type_hour', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approved', models.BooleanField()),
                ('Student_Reflection', models.CharField(max_length=300)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
