# Generated by Django 3.1.1 on 2020-11-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_event_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_student',
            name='Approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Denied')], max_length=30, null=True),
        ),
    ]
